Flowpack:
  EelCraft:
    Neos:
      contextWatcher:
        enable: FALSE
        limit: 1

TYPO3:
  Neos:
    modules:
      administration:
        submodules:
          eelEvaluator:
            label: 'EEL Evaluator'
            controller: '\Flowpack\EelCraft\Neos\Controller\ModuleController'
            description: 'Evaluate EEL expressions and explore results.'
            icon: 'icon-cogs'
            resource: 'Flowpack_EelCraft_Neos_Controller_Module'
