
Flowpack:
  EelCraft:
    Neos:
      contextWatcher:
        enable: false
        limit: 20
TYPO3:
  Neos:
    modules:
      administration:
        submodules:
          eelEvaluator:
            label: 'EEL Evaluator'
            controller: \Flowpack\EelCraft\Neos\Controller\ModuleController
            description: 'Evaluate EEL expressions and explore results.'
            icon: icon-cogs
            privilegeTarget: Flowpack_EelCraft_Neos_Controller_Module
